service: marketing-project

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  environment:
    DB_HOST: database-1.car22e4gqefr.us-east-1.rds.amazonaws.com
    DB_PORT: 3306
    DB_USER: admin
    DB_PASSWORD: admin123
    DB_NAME: marketing-prueba

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  api:
    handler: src/main.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any

package:
  exclude:
    - node_modules/**
    - test/**

